services:
  proxy:
    image: nginx:stable-alpine
    container_name: team-j
    environment:
      - VIRTUAL_HOST=team-j.atd.avans.nl
      - VIRTUAL_PORT=80
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - web
      - client
    restart: unless-stopped
    networks:
      - my-project-network
      - proxy

  web:
    build:
      context: ./Server
      dockerfile: Dockerfile
    environment:
      - ConnectionStrings__MyConnection=${ConnectionStrings__MyConnection}
    restart: unless-stopped
    networks:
      - my-project-network

  client:
    build:
      context: ./Client
      dockerfile: Dockerfile
    depends_on:
      - web
    restart: unless-stopped
    networks:
      - my-project-network

networks:
  my-project-network:
    name: team-j-network
    external: true
  proxy:
    external: true
